FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./

RUN yarn install

COPY . .

RUN yarn build


FROM node:alpine

WORKDIR /app

COPY package*.json ./

RUN yarn install --production=true

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

CMD [ "yarn", "start"]

